In [1]:
import pandas as pd

# read only the first column to get the ids
col1_neg = pd.read_csv("neg_cluster/neg_cluster.tsv", sep="\t", header=None, usecols=[0], dtype=str, names=["id"])
col1_neg["id"] = col1_neg["id"].str.strip()  # remove spaces and newline characters
col1_pos = pd.read_csv("pos_cluster/pos_cluster.tsv", sep="\t", header=None, usecols=[0], dtype=str, names=["id"])
col1_pos["id"] = col1_pos["id"].str.strip()  # remove spaces and newline characters

In [2]:
#checking the negative ids
col1_neg.head(10)

       id
0  A4D2B0
1  Q53FT3
2  Q8IXQ6
3  Q9H790
4  Q969V5
5  O14862
6  O14862
7  O14862
8  O14862
9  O14862

In [3]:
#checking the positive ids
col1_pos.head(10)

       id
0  Q16568
1  Q16627
2  Q16627
3  Q16627
4  Q16627
5  Q16627
6  Q16627
7  Q16627
8  Q16627
9  Q16627

In [4]:
# unique values of the first column of negatives (to take the representative ids only one time)
unique_ids_neg = col1_neg["id"].drop_duplicates()
unique_ids_neg.head(10)
unique_ids_list_neg=unique_ids_neg.values.tolist()

# unique values of the first column of positives (to take the representative ids only one time)
unique_ids_pos = col1_pos["id"].drop_duplicates()
unique_ids_pos.head(10)
unique_ids_list_pos=unique_ids_pos.values.tolist()

In [7]:
#recovering of the entire negative dataset
col2_neg = pd.read_csv("../1.Data_Collection/negative_dataset.tsv", sep="\t")
col2_neg.head(10)

  EntryID  OrganismName  Kingdom  SequenceLength  HelixDomain
0  Q6YN16  Homo sapiens  Metazoa             418        False
1  Q9UHK6  Homo sapiens  Metazoa             382        False
2  A3KMH1  Homo sapiens  Metazoa            1905        False
3  O75874  Homo sapiens  Metazoa             414        False
4  Q9NTK1  Homo sapiens  Metazoa             212        False
5  Q9BTZ2  Homo sapiens  Metazoa             278        False
6  P50542  Homo sapiens  Metazoa             639        False
7  Q99489  Homo sapiens  Metazoa             341        False
8  O00628  Homo sapiens  Metazoa             323        False
9  Q9HCM9  Homo sapiens  Metazoa             518        False

In [8]:
#recovering of the entire positive dataset
col2_pos = pd.read_csv("../1.Data_Collection/positive_dataset.tsv", sep="\t")
col2_pos.head(10)

  EntryID  OrganismName  Kingdom  SequenceLength  SPStart  SPEnd
0  O00300  Homo sapiens  Metazoa             401        1     21
1  O00478  Homo sapiens  Metazoa             584        1     29
2  O00748  Homo sapiens  Metazoa             559        1     26
3  O14763  Homo sapiens  Metazoa             440        1     55
4  O43155  Homo sapiens  Metazoa             660        1     35
5  O43827  Homo sapiens  Metazoa             346        1     26
6  O43866  Homo sapiens  Metazoa             347        1     19
7  O60449  Homo sapiens  Metazoa            1722        1     27
8  O75629  Homo sapiens  Metazoa             220        1     31
9  O94985  Homo sapiens  Metazoa             981        1     28

In [9]:
#Extraction negative representative proteins data and creating of the tsv file
intestation=("EntryID","OrganismName","Kingdom","SequenceLength","HelixDomain")
output_neg_file_name='negative_representative_data.tsv'
with open(output_neg_file_name, "w") as ofs:
        print(*intestation, sep="\t", file=ofs)
        for index,row in col2_neg.iterrows():
          if row['EntryID'] in unique_ids_list_neg:
            print(*row,sep="\t",file=ofs)
        ofs.close

In [10]:
#Extraction positive representative proteins data and creating of the tsv file
intestation=("EntryID","OrganismName","Kingdom","SequenceLength","SPStart","SPEnd")
output_pos_file_name='positive_representative_data.tsv'
with open(output_pos_file_name, "w") as ofs:
        print(*intestation, sep="\t", file=ofs)
        for index,row in col2_pos.iterrows():
          if row['EntryID'] in unique_ids_list_pos:
            print(*row,sep="\t",file=ofs)
        ofs.close

In [11]:
#Checking of the tsv structure of the negative representative proteins data
res_neg = pd.read_csv("negative_representative_data.tsv", sep="\t")
res_neg

,EntryID,OrganismName,Kingdom,SequenceLength,HelixDomain
0,Q6YN16,Homo sapiens,Metazoa,418,False
1,Q9NTK1,Homo sapiens,Metazoa,212,False
2,P50542,Homo sapiens,Metazoa,639,False
3,Q9Y3I1,Homo sapiens,Metazoa,522,False
4,P30044,Homo sapiens,Metazoa,214,False
...,...,...,...,...,...
8920,C0HMD7,Homo sapiens,Metazoa,151,False
8921,P40166,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,100,False
8922,Q02749,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,293,False
8923,P53307,Saccharomyces cerevisiae (strain ATCC 204508 /...,Fungi,113,False
8924,P19407,Spinacia oleracea,Viridiplantae,62,True

In [12]:
#Checking of the tsv structure of the positive representative proteins data
res_pos=pd.read_csv("positive_representative_data.tsv",sep="\t")
res_pos

,EntryID,OrganismName,Kingdom,SequenceLength,SPStart,SPEnd
0,O43155,Homo sapiens,Metazoa,660,1,35
1,O43866,Homo sapiens,Metazoa,347,1,19
2,O75629,Homo sapiens,Metazoa,220,1,31
3,O94985,Homo sapiens,Metazoa,981,1,28
4,P01579,Homo sapiens,Metazoa,166,1,23
...,...,...,...,...,...,...
1088,Q39962,Hevea brasiliensis,Viridiplantae,238,1,31
1089,Q7M3V1,Chelonus sp. nr. curvimaculatus,Metazoa,246,1,20
1090,Q8MMH5,Pimpla hypochondriaca,Metazoa,61,1,20
1091,I6RA76,Scolopendra mutilans,Metazoa,64,1,18
1092,P91629,Drosophila miranda,Metazoa,126,1,16